openapi: 3.0.0
info:
  title: Aliens API
  description: RESTful API that collects Web Engineers' name, favourite tech stack and employment status, built with NodeJS, ExpressJS, Non Relational Database MongoDB and Mongoose Modelling library.
  contact:
    name: Gladwin Tshepo Ramantso
    url: https://gladwinramantso.netlify.app/#home
    email: tshepo.ramantso@outlook.com
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
    variables: {}
paths:
  /aliens:
    get:
      tags:
        - Aliens
      summary: Get all Aliens
      operationId: GetallAliens
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    post:
      tags:
        - Aliens
      summary: Create Alien
      operationId: CreateAlien
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateAlienRequest'
                - example:
                    name: Panky
                    tech_Stack:
                      - JavaScript
                      - TypeScript
                      - HTML
                      - CSS
                      - Technical drawing
                      - UI/UX design
                    isEmployed: true
            example:
              name: Panky
              tech_Stack:
                - JavaScript
                - TypeScript
                - HTML
                - CSS
                - Technical drawing
                - UI/UX design
              isEmployed: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /aliens/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The alien ID
    get:
      tags:
        - Aliens
      summary: Get Single Alien
      operationId: GetSingleAlien
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Aliens
      summary: Update Alien
      operationId: UpdateAlien
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UpdateAlienRequest'
                - example:
                    name: Dumisani Ramantso
            example:
              name: Dumisani Ramantso
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Aliens
      summary: Delete Alien
      operationId: DeleteAlien
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/RegisterUserRequest'
                - example:
                    name: dumisani
                    email: dumisani668@gmail.com
                    password: password123
            example:
              name: dumisani
              email: dumisani668@gmail.com
              password: password123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/LoginUserRequest'
                - example:
                    email: dumisani668@gmail.com
                    password: password123
            example:
              email: dumisani668@gmail.com
              password: password123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    CreateAlienRequest:
      title: CreateAlienRequest
      required:
        - name
        - tech_Stack
        - isEmployed
      type: object
      properties:
        name:
          type: string
        tech_Stack:
          type: array
          items:
            type: string
          description: ''
        isEmployed:
          type: boolean
      example:
        name: Panky
        tech_Stack:
          - JavaScript
          - TypeScript
          - HTML
          - CSS
          - Technical drawing
          - UI/UX design
        isEmployed: true
    UpdateAlienRequest:
      title: UpdateAlienRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: Dumisani Ramantso
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: dumisani
        email: dumisani668@gmail.com
        password: password123
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: dumisani668@gmail.com
        password: password123
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
    description: ''
  - name: Aliens
    description: ''
